org: paravotar
app: para-votar-api
service: para-votar

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
        - 's3:PutObject'
      Resource: "arn:aws:s3:::paravotar/*"
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource: "arn:aws:s3:::*"
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
        - 's3:PutObject'
        - 's3:DeleteObject'
      Resource: "arn:aws:s3:::paravotar-ballots/*"
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
        - 'sqs:ReceiveMessage'
      Resource: 'arn:aws:sqs:*:*:*'

plugins:
  - serverless-dotenv-plugin

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  consulta:
    handler: voterStatus.consulta
    memorySize: 1536
    timeout: 30
    environment:
      DEBUG: true
    events:
      - http:
          path: /consulta
          method: get

  ballotsByTown:
    handler: getBallots.ballotsByTown
    memorySize: 1536
    timeout: 30
    environment:
      DEBUG: true
    events:
      - http:
          path: /ballots/ByTown
          method: get

  ballotsByPrecint:
    handler: getBallots.ballotsByPrecint
    memorySize: 1536
    timeout: 30
    environment:
      DEBUG: true
    events:
      - http:
          path: /ballots/ByPrecint
          method: get

  allBallots:
    handler: getBallots.allBallots
    memorySize: 1536
    timeout: 30
    environment:
      DEBUG: true
    events:
      - http:
          path: /ballots/all
          method: get

  voterCenter:
    handler: centros-de-votacion.voterCenter
    memorySize: 1536
    timeout: 30
    environment:
      DEBUG: true
    events:
      - http:
          path: /voterCenter
          method: get

  createBallotTask:
    handler: generateBallot.createBallotTask
    memorySize: 1536
    timeout: 30
    environment:
      DEBUG: true
    events:
      - http:
          path: /createBallotTask
          method: post

  getPdfUrl:
    handler: pdfUrl.getPdfUrlHandler
    memorySize: 1536
    timeout: 30
    environment:
      DEBUG: true
    events:
      - http:
          path: /getPdfUrl
          method: get

  generatePdf:
    handler: generateBallot.generatePdfHandler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:214416850928:GenerateBallotQueue
          batchSize: 1

  cleanUpPdf:
    handler: generateBallot.cleanUpPdfHandler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:214416850928:BallotCleanUpQueue
          batchSize: 1
